version: '3'

services:
  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:5432 -t 10
        python backend/manage.py runserver 0:8000
    volumes:
      - ./:/app/

  react:
    build: 
      context: .
      dockerfile: ./compose/react/Dockerfile-dev
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/frontend/node_modules
      - ./frontend:/app/frontend

volumes:
  django_sample_db_dev: {}
  node_modules: {}